- name: Install apache2 server
  apt:
     name: apache2
     state: present
     update_cache: yes
  become: yes

- name: Deploy Website in /var/www/
  copy:
     src: "files/{{DOMAINNAME}}"
     dest: /var/www/
     owner: ubuntu
     group: ubuntu
  become: yes

- name: write configuration file
  template: 
     src: templates/default.tmpl.j2
     dest: "/etc/apache2/sites-available/{{DOMAINNAME}}.conf"
  become: yes

- name: enable the site 
  shell: "a2ensite {{DOMAINNAME}}"
  become: yes

- name: reload the daemon
  shell: systemctl daemon-reload
  become: yes

- name: Start service
  service:
     name: apache2
     state: started
